CREATE TABLE IF NOT EXISTS "c_contract"
(
    "id"                       bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"                  bigint   NOT NULL,
    "name"                     varchar  NOT NULL,
    "identity_card"            varchar  NOT NULL,
    "salary"                   varchar  NOT NULL,
    "attach"                   varchar,
    "performance_requirements" varchar,
    "default_clause"           varchar,
    "status"                   varchar  NOT NULL,
    "first_party"              varchar,
    "signed_time"              varchar,
    "start_time"               varchar,
    "end_time"                 varchar,
    "creator"                  varchar           DEFAULT '''',
    "create_time"              datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"                  varchar           DEFAULT '''',
    "update_time"              datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"                  bit      NOT NULL DEFAULT FALSE,
    "tenant_id"                bigint   NOT NULL,
    PRIMARY KEY ("id")
) COMMENT ''合同表单'';

CREATE TABLE IF NOT EXISTS "c_contract_template" (
                                                     "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                     "name" varchar,
                                                     "identity_card" varchar,
                                                     "salary" varchar,
                                                     "attach" varchar,
                                                     "performance_requirements" varchar,
                                                     "default_clause" varchar,
                                                     "status" varchar,
                                                     "first_party" varchar NOT NULL,
                                                     "signed_time" varchar,
                                                     "start_time" varchar,
                                                     "end_time" varchar,
                                                     "creator" varchar DEFAULT '',
                                                     "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                     "updater" varchar DEFAULT '',
                                                     "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                     "deleted" bit NOT NULL DEFAULT FALSE,
                                                     "tenant_id" bigint NOT NULL,
                                                     PRIMARY KEY ("id")
) COMMENT '合同表单模板';
CREATE TABLE IF NOT EXISTS "c_performance_report_request" (
                                                              "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                              "contract_id" bigint NOT NULL,
                                                              "form_ids" varchar NOT NULL,
                                                              "start_time" varchar NOT NULL,
                                                              "end_time" varchar,
                                                              "notify_time" varchar,
                                                              "notify_duration" varchar,
                                                              "creator" varchar DEFAULT '',
                                                              "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                              "updater" varchar DEFAULT '',
                                                              "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                              "deleted" bit NOT NULL DEFAULT FALSE,
                                                              "tenant_id" bigint NOT NULL,
                                                              PRIMARY KEY ("id")
) COMMENT '业绩定义表';
CREATE TABLE IF NOT EXISTS "c_bpm_form" (
                                            "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                            "type" int NOT NULL,
                                            "result" int NOT NULL,
                                            "process_instance_id" varchar,
                                            "creator" varchar DEFAULT '',
                                            "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "updater" varchar DEFAULT '',
                                            "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                            "deleted" bit NOT NULL DEFAULT FALSE,
                                            "tenant_id" bigint NOT NULL,
                                            PRIMARY KEY ("id")
) COMMENT 'bpm和业务表单之间的关联表';