-- 将该建表 SQL 语句，添加到 yudao-module-c-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "c_bpm_form" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" int NOT NULL,
    "result" int NOT NULL,
    "process_instance_id" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT 'bpm和业务表单之间的关联表';

-- 将该删表 SQL 语句，添加到 yudao-module-c-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "c_bpm_form";
